require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  NewCops: enable

# ----------------------- Style -----------------------

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# ----------------------- Layout ----------------------

Layout/LineLength:
  Max: 120

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - nostr.gemspec

# ----------------------- RSpec -----------------------

RSpec/ExampleLength:
  Enabled: false
