inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - docs/**/*

# ----------------------- Gemspec -----------------------

Gemspec/DevelopmentDependencies:
  Enabled: false

# ----------------------- Style -----------------------

Style/RaiseArgs:
  Exclude:
    - 'lib/nostr/key.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# ----------------------- Layout ----------------------

Layout/LineLength:
  Max: 120

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - nostr.gemspec

Metrics/ParameterLists:
  CountKeywordArgs: false

# ----------------------- RSpec -----------------------

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - spec/nostr/errors/invalid_*

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/nostr/errors/invalid_*

# ----------------------- Naming -----------------------

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'spec/nostr/key.rb'
