module Nostr
  class Crypto
    BN_BASE: 0 | 2 | 10 | 16
    CIPHER_CURVE: String
    CIPHER_ALGORITHM: String

    def encrypt_text: (PrivateKey, PublicKey, String) -> String
    def decrypt_text: (PrivateKey, PublicKey, String) -> String
    def sign_event: (Event, PrivateKey) -> Event
    def sign_message: (String, PrivateKey) -> Signature
    def valid_sig?: (String, PublicKey, Signature) -> bool
    def check_sig!: (String, PublicKey, Signature) -> bool

    private

    def compute_shared_key: (PrivateKey, PublicKey) -> String
    def hash_event:(Event) -> String
  end
end
