module Nostr
  class Key
    FORMAT: Regexp
    LENGTH: int

    def self.from_bech32: (String) -> Key
    def self.hrp: -> String

    def initialize: (String) -> PrivateKey
    def to_bech32: -> String

    private

    def validate_hex_value: (String) -> nil
  end
end
