# Classes
module Nostr
  class KeyPair
    attr_reader private_key: PrivateKey
    attr_reader public_key: PublicKey

    def initialize: (private_key: PrivateKey, public_key: PublicKey) -> KeyPair
  end
end
