# Classes
module Nostr
  class User
    attr_reader keypair: KeyPair

    def initialize: (?keypair: KeyPair | nil, ?keygen: Keygen) -> void
    def create_event: (
      kind: Integer,
      content: String,
      ?created_at: Integer,
      ?tags: Array[Array[String]],
    ) -> Event

    private

    def sign: (String event_sha256) -> String
  end
end
